version: '3'
services:
  hits:
    image: 2ti2225gz2/homework-5_145
    ports:
      - 5000:5000
    networks:
      - network-5
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - network-5
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local

networks:
  netvork-5:
   driver: bridge
